---
marp: true
theme: gaia
footer: ''
paginate: true
size: 16:9
math: katex
---
# `switch`
首先对括号里的表达式求值，**可以是一个初始化的变量声明**
`case`标签必须是**整型常量**表达式
跳转到某个特定的`case`，则该`case`标签前的部分会**被忽略掉**
如果要在`case`中定义变量，应该**把变量定义在块内**

# `while`
条件部分可以是一个表达式或*一个带初始化的变量声明*
**定义在`while`条件部分或者`while`循环体内的变量每次迭代都经历从创建到销毁的过程**

# `for`
## `for`语句头中的多重定义
可以定义多个对象，**只能有一条声明语句**，所以，所有变量的基础类型必须相同

# `do while`
条件不能为空
条件使用的变量必须定义在循环体之外
不允许在条件部分定义变量

# try语句块和异常处理
异常是指存在于运行时的反常行为，典型的异常有失去数据库连接和遇到意外输入等。

C++的异常处理机制为异常检测和异常处理提供支持，它包括：
1. `throw`表达式：异常检测部分使用`throw`表达式来表示遇到了无法处理的问题。称为`throw`引发了异常。
2. `try`语句块：异常处理部分使用`try`语句块处理异常。`try`语句块以关键字`try`开始，以**一个或多个**`catch`子句结束。
3. 一套异常类：用于在`throw`表达式和相关的`catch`子句间传递异常的具体信息。

## `throw`表达式
`throw`表达式包含关键字`throw`和紧随其后的一个表达式，表达式的类型就是抛出的异常类型。
即`throw`后面跟一个异常类型的对象，给它提供一个`string`对象或C风格字符串对其初始化。
```
throw runtime_error("Data must be same as size");//使用 throw 表达式抛出一个运行时错误。
```

## try语句块
跟在`try`块后面的是一个或多个`catch`子句。`catch`子句包括三部分：关键字 `catch`、括号内一个异常类型的对象的声明（叫做异常声明）、一个块。

当`try`语句块中抛出了一个异常，如果该异常类型与`catch`子句括号中的异常类型相同，就会执行该`catch`子句。

`catch`一旦完成，程序就跳转到`try`语句块最后一个`catch`子句之后的那条语句继续执行。

在`catch`后面的括号里使用省略号(`...`)可以让`catch`捕获所有类型的异常。

每个标准库异常类都有一个`what`成员函数，它没有参数，返回初始化该对象时所用的 C 风格字符串。

```
try{
   throw runtime_error("Data must be same as size");//try 语句块抛出了一个异常
}
catch(runtime_error err)//在 catch 后面的括号中声明了一个“runtime_error”类型的对象，与 try 抛出的异常类型相同，接下来执行此子句。
{
    cout << err.what();//输出 "Data must be same as size"
}//
```

## 函数在寻找处理代码的过程中退出

`throw`语句可能出现在嵌套的`try`语句块中或在`try`语句块中调用的某个函数内。当异常被抛出，程序会**从内到外**一层层寻找相应类型的`catch`子句。如果最后还是没找到，系统会调用`terminate`函数并终止当前程序的执行。*程序非正常退出*

如果`throw`语句外就没有`try`语句块，也会执行`terminate`函数。

理解：异常中断了程序的正常流程。当发生异常，程序执行到一半就中断了，可能会存在如资源没有正常释放，对象没有处理完成等情况。*异常安全*的代码要求在异常发生时能正确执行清理工作。这个非常困难。

## 标准异常
C++ 标准库定义了一组异常类，用于报告标准库函数遇到的问题。他们定义在 4 个头文件中：
1. `exception`头文件定义了最通用的异常类`exception`.它只报告异常的发生，不提供任何额外信息。
2. `stdexcept`头文件
3. `new`头文件定义了`bad_alloc`异常类型
4. `type_info`头文件定义了`bad_cast`异常类型


定义在`stdexcept`头文件中的类型必须使用`string`对象或 C 风格字符串来初始化他们。其他 3 个头文件中的 3 中类型则只能默认初始化，不能提供初始值。
### stdexcept定义的异常类
|stdexcept定义的异常类|解释|
|:--|:--|
| exception | 最常见的问题 |
|runtime_error|只有在运行时才能检测出的问题|
| range_error | 运行时错误：生成的结果超出了有意义的值域范围 |
|overflow_error| 运行时错误：计算上溢|
|underflow_error|运行时错误：计算下溢|
|logic_error|程序逻辑错误|
|domain_error|逻辑错误：参数对应的结果值不存在|
|invalid_argument|逻辑错误：无效参数|
|length_error|逻辑错误：试图创建一个超出该类型最大长度的对象|
|out_of_range|逻辑错误：使用一个超出有效范围的值|

异常类型只有一个`what`成员函数，该函数没有参数，返回是一个 C 风格字符串的指针，目的是提供关于异常的文本信息。

对于无初始值的异常类型，`what`返回的内容由编译器决定，有初始值的返回初始值。

